# Generated by Django 4.1.1 on 2023-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('availability', models.BooleanField()),
                ('rentalStart', models.DateTimeField()),
                ('rentalEnd', models.DateTimeField()),
                ('checkoutCode', models.IntegerField()),
                ('stranded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('usernm', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
