# Generated by Django 4.1.1 on 2023-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(default='Customer', max_length=50),
        ),
    ]
