# Generated by Django 4.1.1 on 2023-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rentalEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='rentalStart',
            field=models.DateTimeField(),
        ),
    ]
