# Generated by Django 4.1.1 on 2023-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0002_alter_car_cost_alter_user_money_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imageURL',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='stranded',
            field=models.BooleanField(default=False),
        ),
    ]
