# Generated by Django 4.1.1 on 2023-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0003_car_imageurl_alter_car_stranded'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
    ]
