# Generated by Django 4.1.1 on 2023-03-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0003_car_strandedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='verdeCarsPages.user'),
        ),
    ]
