# Generated by Django 4.1.1 on 2023-03-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0005_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
