# Generated by Django 4.1.1 on 2023-03-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0004_car_renter'),
        ('verdeCarsPages', '0006_user_checkoutcode_user_hoursworked'),
    ]

    operations = [
    ]
