# Generated by Django 4.1.1 on 2023-03-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0006_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
    ]
