# Generated by Django 4.0.2 on 2023-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0007_merge_20230320_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rentalEnd',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rentalStart',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
