# Generated by Django 4.1.1 on 2023-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0008_rename_availability_car_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
        migrations.AlterField(
            model_name='car',
            name='rentalStart',
            field=models.DateField(),
        ),
    ]
