# Generated by Django 4.0.2 on 2023-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0008_alter_car_rentalend_alter_car_rentalstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='checkoutCode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
