# Generated by Django 4.0.2 on 2023-04-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0009_alter_car_checkoutcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isCheckedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='000-000-0000', max_length=12),
        ),
    ]
