# Generated by Django 4.0.2 on 2023-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0011_rename_ischeckedout_car_isrented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='strandedAddress',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
