# Generated by Django 4.0.2 on 2023-04-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0010_car_insured_alter_user_phonenumber'),
        ('verdeCarsPages', '0013_alter_car_strandedaddress'),
    ]

    operations = [
    ]
