# Generated by Django 4.1.1 on 2023-04-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0010_alter_user_phonenumber'),
        ('verdeCarsPages', '0014_merge_20230415_1325'),
    ]

    operations = [
    ]
