# Generated by Django 4.0.2 on 2023-04-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdeCarsPages', '0014_merge_20230414_2137'),
        ('verdeCarsPages', '0015_merge_20230415_1938'),
    ]

    operations = [
    ]
